apiVersion: apps/v1
kind: Deployment
metadata:
  name: inner-consulting-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inner-consulting-app
  template:
    metadata:
      labels:
        app: inner-consulting-app
    spec:
      containers:
        - name: inner-consulting-app
          image: inner-consulting-test
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: inner-consulting-app-service
spec:
  selector:
    app: inner-consulting-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
